version: '2'

volumes:
  django_data: {}
  postgres_data: {}
  postgres_backup: {}
  public_data: {}

services:

  postgres:
    restart: always
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/network/backups
    env_file: .env

  redis:
    restart: always
    build: ./compose/redis

  django:
    restart: always
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: /usr/local/bin/supervisord -c /supervisord.conf --nodaemon
    depends_on:
      - postgres
      - redis
    env_file: .env
    volumes:
      - django_data:/network/data
      - public_data:/network/public
      - postgres_backup:/network/backups

  nginx:
    restart: always
    build: ./compose/nginx
    depends_on:
      - django
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - public_data:/network/public
