# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-18 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='consortial_id',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='consortial_id',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together=set([('experiment', 'consortial_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='experiment',
            unique_together=set([('project', 'consortial_id')]),
        ),
    ]
