# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneannotation',
            name='enhancers',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='enhancers', to='network.GenomicRegions'),
        ),
        migrations.AlterField(
            model_name='geneannotation',
            name='gtf_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='geneannotation',
            name='promoters',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='promoters', to='network.GenomicRegions'),
        ),
        migrations.AlterField(
            model_name='genomeassembly',
            name='default_annotation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='network.GeneAnnotation'),
        ),
    ]
