# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-18 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20171218_1030'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metaplot',
            unique_together=set([('locus_group', 'dataset')]),
        ),
    ]
