# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20161025_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosome', models.CharField(max_length=32)),
                ('strand', models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='exon',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='chromosome',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='end',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='start',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='strand',
        ),
        migrations.AddField(
            model_name='transcript',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Gene'),
        ),
        migrations.AddField(
            model_name='exon',
            name='transcript',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='network.Transcript'),
            preserve_default=False,
        ),
    ]
