# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20161025_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='aliases',
        ),
        migrations.AddField(
            model_name='gene',
            name='name',
            field=models.CharField(default='gene', max_length=32),
            preserve_default=False,
        ),
    ]
