# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20161025_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='name',
            field=models.CharField(default='transcript', max_length=32),
            preserve_default=False,
        ),
    ]
