# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 19:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_transcript_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exon',
            name='transcript',
        ),
        migrations.AddField(
            model_name='transcript',
            name='exons',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2), default=[[0, 0]], size=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Exon',
        ),
    ]
