# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-26 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20180103_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assembly',
            options={'verbose_name_plural': 'Assemblies'},
        ),
        migrations.AlterModelOptions(
            name='locus',
            options={'verbose_name': 'Locus', 'verbose_name_plural': 'Loci'},
        ),
        migrations.AlterModelOptions(
            name='metaplot',
            options={'verbose_name': 'Metaplot', 'verbose_name_plural': 'Metaplots'},
        ),
        migrations.AlterModelOptions(
            name='ontology',
            options={'verbose_name': 'Ontology', 'verbose_name_plural': 'Ontologies'},
        ),
        migrations.AlterModelOptions(
            name='pca',
            options={'verbose_name': 'PCA', 'verbose_name_plural': 'PCAs'},
        ),
        migrations.AlterModelOptions(
            name='pcatransformedvalues',
            options={'verbose_name': 'PCA Transformed Values', 'verbose_name_plural': 'PCA Transformed Values'},
        ),
        migrations.AddField(
            model_name='dataset',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiment',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
    ]
