# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 16:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20161025_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntersectionValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_start', models.IntegerField()),
                ('relative_end', models.IntegerField()),
                ('intersection_values', django.contrib.postgres.fields.jsonb.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('genomic_regions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.GenomicRegions')),
            ],
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='intersection_values',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='enhancer_metaplot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhancer', to='network.MetaPlot'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='owners',
            field=models.ManyToManyField(blank=True, to='network.MyUser'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='promoter_metaplot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoter', to='network.MetaPlot'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='enhancer_intersection',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='enhancer', to='network.IntersectionValues'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='promoter_intersection',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='promoter', to='network.IntersectionValues'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='intersectionvalues',
            unique_together=set([('genomic_regions', 'relative_start', 'relative_end')]),
        ),
    ]
