# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-31 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20180126_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_action', models.BooleanField(default=False)),
                ('action', models.CharField(choices=[('added', 'added'), ('created', 'created'), ('favorited', 'favorited')], max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Dataset')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Experiment')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='network.MyUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to='network.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
