# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 18:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20161031_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='owners',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
