# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-02 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_activity_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='locusgroup',
            name='intersection_bed_path',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locusgroup',
            name='metaplot_bed_path',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
