# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20161031_1450'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='intersectionvalues',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='metaplot',
            unique_together=set([]),
        ),
    ]
