# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-05 19:11
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20180202_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='pca',
            name='neural_network',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pca',
            name='neural_network_scaler',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
    ]
