# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20161031_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='intersectionvalues',
            name='bigwig_url',
            field=models.URLField(default='temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metaplot',
            name='bigwig_url',
            field=models.URLField(default='temp'),
            preserve_default=False,
        ),
    ]
