# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-07 14:09
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20180305_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pca',
            name='pca',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
    ]
