# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-07 14:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_auto_20180307_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pca',
            name='plot',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
