# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_auto_20161031_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='correlationcell',
            name='genomic_regions',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='network.GenomicRegions'),
            preserve_default=False,
        ),
    ]
