# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_correlationcell_genomic_regions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='correlationcell',
            unique_together=set([('x_dataset', 'y_dataset', 'genomic_regions')]),
        ),
    ]
