# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-08 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20180307_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetdatadistance',
            name='recommended',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasetmetadatadistance',
            name='recommended',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
