# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-15 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20180314_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_type', models.CharField(choices=[('primary', 'primary'), ('metadata', 'metadata')], max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('recommended_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_dataset', to='network.Dataset')),
                ('recommended_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_experiment', to='network.Experiment')),
                ('referring_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referring_dataset', to='network.Dataset')),
                ('referring_experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referring_experiment', to='network.Experiment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_type', models.CharField(choices=[('primary', 'primary'), ('metadata', 'metadata')], max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('dataset_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset_1', to='network.Dataset')),
                ('dataset_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset_2', to='network.Dataset')),
                ('experiment_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_1', to='network.Experiment')),
                ('experiment_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_2', to='network.Experiment')),
            ],
        ),
    ]
