# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20161117_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='antibody',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
