# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_auto_20161118_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='enhancer_intersection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enhancer', to='network.IntersectionValues'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='enhancer_metaplot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enhancer', to='network.MetaPlot'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='promoter_intersection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promoter', to='network.IntersectionValues'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='promoter_metaplot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promoter', to='network.MetaPlot'),
        ),
    ]
