# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-19 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_auto_20180319_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetaccess',
            old_name='view_count',
            new_name='access_count',
        ),
        migrations.RenameField(
            model_name='experimentaccess',
            old_name='view_count',
            new_name='access_count',
        ),
    ]
