# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-21 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_auto_20180319_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='referring_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referring_user', to='network.MyUser'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='rec_type',
            field=models.CharField(choices=[('primary', 'primary'), ('metadata', 'metadata'), ('user', 'user')], max_length=32),
        ),
    ]
