# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-22 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_auto_20180321_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='admin_action',
            new_name='administrative_action',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='action',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='owner',
        ),
        migrations.AddField(
            model_name='activity',
            name='created_experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_experiment', to='network.Experiment'),
        ),
        migrations.AddField(
            model_name='activity',
            name='favorited_experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_experiment', to='network.Experiment'),
        ),
        migrations.AddField(
            model_name='activity',
            name='followed_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed_user', to='network.MyUser'),
        ),
        migrations.AddField(
            model_name='activity',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.MyUser'),
        ),
    ]
