# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_auto_20170203_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='name',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
