# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_auto_20170203_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='antibody',
            new_name='target',
        ),
    ]
