# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_auto_20170203_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
