# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_auto_20170206_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='data_type',
            field=models.CharField(choices=[('RAMPAGE', 'RAMPAGE'), ('RNA-seq', 'RNA-seq'), ('HiC', 'HiC'), ('RNA-PET', 'RNA-PET'), ('DNase-seq', 'DNase-seq'), ('siRNA knockdown followed by RNA-seq', 'siRNA knockdown followed by RNA-seq'), ('eCLIP', 'eCLIP'), ('ChIA-PET', 'ChIA-PET'), ('shRNA knockdown followed by RNA-seq', 'shRNA knockdown followed by RNA-seq'), ('single cell isolation followed by RNA-seq', 'single cell isolation followed by RNA-seq'), ('Repli-chip', 'Repli-chip'), ('CRISPR genome editing followed by RNA-seq', 'CRISPR genome editing followed by RNA-seq'), ('RIP-seq', 'RIP-seq'), ('whole-genome shotgun bisulfite sequencing', 'whole-genome shotgun bisulfite sequencing'), ('ATAC-seq', 'ATAC-seq'), ('CAGE', 'CAGE'), ('MNase-seq', 'MNase-seq'), ('FAIRE-seq', 'FAIRE-seq'), ('ChIP-seq', 'ChIP-seq'), ('Repli-seq', 'Repli-seq'), ('microRNA-seq', 'microRNA-seq')], max_length=64),
        ),
    ]
