# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_auto_20170206_1609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataFavorite',
            new_name='ExperimentFavorite',
        ),
        migrations.RenameModel(
            old_name='DataRecommendation',
            new_name='ExperimentRecommendation',
        ),
        migrations.AlterModelOptions(
            name='experiment',
            options={'get_latest_by': 'created'},
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='cell_type',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='target',
        ),
        migrations.AddField(
            model_name='correlationcell',
            name='x_experiment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='x', to='network.Experiment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correlationcell',
            name='y_experiment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='y', to='network.Experiment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='cell_type',
            field=models.CharField(default='temp', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='data_type',
            field=models.CharField(choices=[('RAMPAGE', 'RAMPAGE'), ('RNA-seq', 'RNA-seq'), ('HiC', 'HiC'), ('RNA-PET', 'RNA-PET'), ('DNase-seq', 'DNase-seq'), ('siRNA knockdown followed by RNA-seq', 'siRNA knockdown followed by RNA-seq'), ('eCLIP', 'eCLIP'), ('ChIA-PET', 'ChIA-PET'), ('shRNA knockdown followed by RNA-seq', 'shRNA knockdown followed by RNA-seq'), ('single cell isolation followed by RNA-seq', 'single cell isolation followed by RNA-seq'), ('Repli-chip', 'Repli-chip'), ('CRISPR genome editing followed by RNA-seq', 'CRISPR genome editing followed by RNA-seq'), ('RIP-seq', 'RIP-seq'), ('whole-genome shotgun bisulfite sequencing', 'whole-genome shotgun bisulfite sequencing'), ('ATAC-seq', 'ATAC-seq'), ('CAGE', 'CAGE'), ('MNase-seq', 'MNase-seq'), ('FAIRE-seq', 'FAIRE-seq'), ('ChIP-seq', 'ChIP-seq'), ('Repli-seq', 'Repli-seq'), ('microRNA-seq', 'microRNA-seq')], default='ChIP-seq', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='target',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='experimentfavorite',
            name='favorite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Experiment'),
        ),
        migrations.AlterField(
            model_name='experimentrecommendation',
            name='recommended',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Experiment'),
        ),
        migrations.AlterField(
            model_name='experimentrecommendation',
            name='reference_dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='network.Experiment'),
        ),
        migrations.AlterUniqueTogether(
            name='correlationcell',
            unique_together=set([('x_experiment', 'y_experiment', 'genomic_regions')]),
        ),
        migrations.RemoveField(
            model_name='correlationcell',
            name='x_dataset',
        ),
        migrations.RemoveField(
            model_name='correlationcell',
            name='y_dataset',
        ),

    ]
