# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-24 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def associate_organisms(apps, schema_editor):

    Organism = apps.get_model('network', 'Organism')
    Assembly = apps.get_model('network', 'Assembly')

    human = Organism.objects.get_or_create(name='Homo sapiens')[0]
    mouse = Organism.objects.get_or_create(name='Mus musculus')[0]
    fly = Organism.objects.get_or_create(name='Drosophila melanogaster')[0]
    worm = Organism.objects.get_or_create(name='Caenorhabditis elegans')[0]

    for assembly in Assembly.objects.all():

        if assembly.name in ['hg19', 'GRCh38']:
            assembly.organism = human
            assembly.save()
        elif assembly.name in ['mm9', 'mm10']:
            assembly.organism = mouse
            assembly.save()
        elif assembly.name in ['dm3', 'dm6']:
            assembly.organism = fly
            assembly.save()
        elif assembly.name in ['ce10', 'ce11']:
            assembly.organism = worm
            assembly.save()


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_auto_20180424_1525'),
    ]

    operations = [

        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(associate_organisms),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='assembly',
                    name='organism',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Organism'),
                ),
            ]),
    ]
