# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-26 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0027_network'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='exp_type',
            new_name='experiment_type',
        ),
    ]
