# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0027_experiment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.Project'),
        ),
    ]
