# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-04 19:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0028_auto_20180426_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_plot', django.contrib.postgres.fields.jsonb.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_plot', django.contrib.postgres.fields.jsonb.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Experiment')),
            ],
        ),
        migrations.RenameModel(
            old_name='Network',
            new_name='OrganismNetwork',
        ),
    ]
