# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0029_remove_dataset_owners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentrecommendation',
            old_name='reference_dataset',
            new_name='reference_experiment',
        ),
    ]
