# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-09 19:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0029_auto_20180504_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dendrogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dendrogram_plot', django.contrib.postgres.fields.jsonb.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('experiment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.ExperimentType')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Organism')),
            ],
        ),
    ]
