# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-14 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0030_dendrogram'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='similarity',
            unique_together=set([('sim_type', 'experiment_1', 'experiment_2', 'dataset_1', 'dataset_2')]),
        ),
    ]
