# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0030_auto_20170212_1401'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CorrelationCell',
            new_name='ExperimentCorrelation',
        ),
    ]
