# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0031_auto_20170214_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='enhancer_intersection',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='enhancer_metaplot',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='promoter_intersection',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='promoter_metaplot',
        ),
        migrations.RemoveField(
            model_name='experimentrecommendation',
            name='reference_experiment',
        ),
        migrations.RemoveField(
            model_name='geneannotation',
            name='enhancers',
        ),
        migrations.RemoveField(
            model_name='geneannotation',
            name='promoters',
        ),
        migrations.RemoveField(
            model_name='intersectionvalues',
            name='bigwig_url',
        ),
        migrations.RemoveField(
            model_name='intersectionvalues',
            name='relative_end',
        ),
        migrations.RemoveField(
            model_name='intersectionvalues',
            name='relative_start',
        ),
        migrations.RemoveField(
            model_name='metaplot',
            name='bigwig_url',
        ),
        migrations.RemoveField(
            model_name='metaplot',
            name='relative_end',
        ),
        migrations.RemoveField(
            model_name='metaplot',
            name='relative_start',
        ),
        migrations.AddField(
            model_name='experiment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentrecommendation',
            name='collaborative_experiment',
            field=models.ForeignKey(default=151, on_delete=django.db.models.deletion.CASCADE, related_name='collaborative', to='network.Experiment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentrecommendation',
            name='collaborative_rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentrecommendation',
            name='correlation_experiment',
            field=models.ForeignKey(default=151, on_delete=django.db.models.deletion.CASCADE, related_name='correlation', to='network.Experiment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentrecommendation',
            name='correlation_rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentrecommendation',
            name='metadata_experiment',
            field=models.ForeignKey(default=151, on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='network.Experiment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentrecommendation',
            name='metadata_rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genomicregions',
            name='short_label',
            field=models.CharField(default='temp', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intersectionvalues',
            name='dataset',
            field=models.ForeignKey(default=150, on_delete=django.db.models.deletion.CASCADE, to='network.Dataset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metaplot',
            name='dataset',
            field=models.ForeignKey(default=150, on_delete=django.db.models.deletion.CASCADE, to='network.Dataset'),
            preserve_default=False,
        ),
    ]
