# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0033_remove_experimentrecommendation_collaborative_experiment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experimentrecommendation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userrecommendation',
            options={},
        ),
        migrations.RemoveField(
            model_name='experimentrecommendation',
            name='score',
        ),
        migrations.RemoveField(
            model_name='userrecommendation',
            name='score',
        ),
    ]
