# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-12 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0034_auto_20180530_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='pca',
            name='neural_network_file',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to='nn_models/'),
        ),
    ]
