# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0034_auto_20170228_1605'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='experimentrecommendation',
            unique_together=set([('owner', 'recommended')]),
        ),
    ]
