# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-27 20:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0036_dataset_filtered_intersection_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_field', models.CharField(choices=[('cell_type', 'cell_type'), ('target', 'target')], max_length=24)),
                ('neural_network_file', models.FileField(blank=True, max_length=256, null=True, upload_to='neural_networks/')),
                ('neural_network_scaler', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
                ('neural_network_categories', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('experiment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.ExperimentType')),
                ('locus_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.LocusGroup')),
            ],
        ),
    ]
