# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-27 21:46
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0038_auto_20180627_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neuralnetwork',
            name='neural_network_label_encoder',
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='neural_network_label_binarizer',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
    ]
