# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-02 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0040_auto_20180628_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuralnetwork',
            name='loss',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
