# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-16 19:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0041_neuralnetwork_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='predicted_cell_type_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='predicted_target_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
