# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-08-22 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def associate_organisms(apps, schema_editor):

    Organism = apps.get_model('network', 'Organism')
    Experiment = apps.get_model('network', 'Experiment')
    Dataset = apps.get_model('network', 'Dataset')

    human = Organism.objects.get_or_create(name='Homo sapiens')[0]
    mouse = Organism.objects.get_or_create(name='Mus musculus')[0]
    fly = Organism.objects.get_or_create(name='Drosophila melanogaster')[0]
    worm = Organism.objects.get_or_create(name='Caenorhabditis elegans')[0]

    for experiment in Experiment.objects.all():

        ds = Dataset.objects.filter(experiment=experiment)[0]

        if ds.assembly.name in ['hg19', 'GRCh38']:
            experiment.organism = human
            experiment.save()
        elif ds.assembly.name in ['mm9', 'mm10']:
            experiment.organism = mouse
            experiment.save()
        elif ds.assembly.name in ['dm3', 'dm6']:
            experiment.organism = fly
            experiment.save()
        elif ds.assembly.name in ['ce10', 'ce11']:
            experiment.organism = worm
            experiment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0044_experiment_organism'),
    ]

    operations = [

        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(associate_organisms),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='experiment',
                    name='organism',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='network.Organism',
                    ),
                ),
            ]),
    ]
