# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-24 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0047_auto_20190114_2031'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together=set([('experiment', 'consortial_id', 'ambiguous_url', 'plus_url', 'minus_url')]),
        ),
    ]
