# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-04-14 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0048_auto_20190224_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='consortial_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='consortial_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together=set([('experiment', 'consortial_id')]),
        ),
    ]
