# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-04-20 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0049_auto_20190414_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='consortial_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Repository ID'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='consortial_url',
            field=models.URLField(blank=True, null=True, verbose_name='Repository URL'),
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together=set([('experiment', 'consortial_id', 'ambiguous_url', 'plus_url', 'minus_url')]),
        ),
    ]
